In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
tf.__version__

'2.2.0'

In [3]:
keras.__version__

'2.3.0-tf'

In [23]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

In [24]:
y_test

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [5]:
X_train_full.shape

(60000, 28, 28)

In [6]:
X_train_full.dtype

dtype('uint8')

In [7]:
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [8]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(300, activation='relu'))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

In [10]:
keras.utils.plot_model(model)

# Shit

Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.layers

In [17]:
weights,bias = model.layers[1].get_weights()

In [18]:
weights

array([[-0.0726575 , -0.04742591,  0.07113157, ...,  0.05300653,
         0.06494641, -0.05050535],
       [ 0.02793937, -0.06843223,  0.05707008, ...,  0.0003235 ,
         0.01158246,  0.02877956],
       [ 0.02261531,  0.03574282,  0.0509188 , ...,  0.06756806,
         0.06799287,  0.04289329],
       ...,
       [ 0.01481288, -0.06478076,  0.00573151, ..., -0.0144044 ,
        -0.04034159, -0.0694186 ],
       [ 0.05001119,  0.06712756, -0.02826774, ...,  0.0448533 ,
         0.00658204,  0.05554356],
       [ 0.02859712, -0.02880381,  0.06639153, ..., -0.0137669 ,
         0.05084114,  0.0110278 ]], dtype=float32)

In [19]:
bias

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [20]:
weights.shape

(784, 300)

In [21]:
bias.shape

(300,)

In [28]:
model.compile(optimizer=keras.optimizers.SGD(), loss = 'sparse_categorical_crossentropy',
             metrics = ['accuracy'])

In [29]:
history = model.fit(X_train, y_train, epochs=30, validation_data=(X_valid, y_valid))

Epoch 1/30
1719/1719 [==============================] - 6s 4ms/step - loss: 0.7059 - accuracy: 0.7689 - val_loss: 0.5621 - val_accuracy: 0.8074
Epoch 2/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4831 - accuracy: 0.8331 - val_loss: 0.4715 - val_accuracy: 0.8390
Epoch 3/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4380 - accuracy: 0.8473 - val_loss: 0.4156 - val_accuracy: 0.8582
Epoch 4/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4119 - accuracy: 0.8559 - val_loss: 0.4346 - val_accuracy: 0.8470
Epoch 5/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.3926 - accuracy: 0.8619 - val_loss: 0.4019 - val_accuracy: 0.8608
Epoch 6/30
1719/1719 [==============================] - 6s 4ms/step - loss: 0.3766 - accuracy: 0.8683 - val_loss: 0.3793 - val_accuracy: 0.8708
Epoch 7/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.3633 - accuracy: 0.8715 - val_loss: 0.3726 - val_accuracy: