In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
X = tf.range(10)

In [4]:
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [5]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [6]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [8]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [9]:
dataset = dataset.repeat(3).batch(7, drop_remainder=True)
# drop_remainder will drop the last batch whose size is less than 7

In [10]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [11]:
dataset

<BatchDataset shapes: (7,), types: tf.int32>

In [12]:
dataset = dataset.map(lambda x : x*2)