In [7]:
import tensorflow as tf

In [9]:
tf.__version__

'2.2.0-rc2'

In [10]:
X = tf.range(10)

In [11]:
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [37]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [30]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [31]:
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [32]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [38]:
dataset = dataset.repeat(3).batch(7, drop_remainder=True)
# drop_remainder will drop the last batch whose size is less than 7

In [39]:
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
