In [16]:
import tensorflow as tf

In [17]:
tf.__version__

'2.3.1'

In [18]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [19]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [20]:
t = tf.constant(([1,2,3],[4,5,6]))

In [21]:
t.shape

TensorShape([2, 3])

In [22]:
t.dtype

tf.int32

In [23]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [24]:
t[...,1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [25]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [26]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [30]:
t @ tf.transpose(t+2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 26,  44],
       [ 62, 107]])>

In [15]:
tf.constant(2.) + tf.constant(42)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [31]:
t2 = tf.constant(40., dtype = tf.float64)

In [33]:
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [34]:
# Variables

In [42]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])

In [43]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [46]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

In [48]:
v[0,1].assign(32)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4., 32., 12.],
       [16., 20., 24.]], dtype=float32)>

In [52]:
v[:,2].assign([69,96])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4., 32., 69.],
       [16., 20., 96.]], dtype=float32)>

In [54]:
v.scatter_nd_update(indices=[[0,0],[1,2]], updates=[100,200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  32.,  69.],
       [ 16.,  20., 200.]], dtype=float32)>